terminate called after throwing an instance of 'std::runtime_error'
  what():  Model file doesn't exist
